import { ImageResponse } from 'next/og';

// Open Graph + Twitter card image, generated by Next.js at build time.
// 1200x630 is the canonical OG dimensions; renders identically on
// Twitter, LinkedIn, Slack, iMessage previews.

export const alt = 'Meo — Metabolic Intelligence System';
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

export default async function OGImage() {
  return new ImageResponse(
    (
      <div
        style={{
          height: '100%',
          width: '100%',
          background:
            'linear-gradient(135deg, #1c4a40 0%, #0f2a24 60%, #143730 100%)',
          color: '#ffffff',
          display: 'flex',
          flexDirection: 'column',
          padding: '64px 72px',
          fontFamily: 'sans-serif',
          position: 'relative',
        }}
      >
        {/* Decorative droplet glow */}
        <div
          style={{
            position: 'absolute',
            top: -180,
            right: -180,
            width: 480,
            height: 480,
            borderRadius: 480,
            background:
              'radial-gradient(circle at 50% 50%, rgba(164,214,94,0.32) 0%, rgba(164,214,94,0) 70%)',
            display: 'flex',
          }}
        />

        {/* Brand */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 8,
            fontSize: 28,
            fontWeight: 700,
            letterSpacing: 0.3,
          }}
        >
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
            }}
          >
            <span>Me</span>
            <svg
              width="28"
              height="28"
              viewBox="0 0 24 24"
              style={{ marginLeft: 4, marginRight: 16 }}
            >
              <path
                d="M12 2C12 2 5 10 5 15C5 19.4183 8.13401 23 12 23C15.866 23 19 19.4183 19 15C19 10 12 2 12 2Z"
                fill="#a4d65e"
              />
            </svg>
          </div>
          <span
            style={{
              fontSize: 14,
              letterSpacing: 2,
              color: 'rgba(255,255,255,0.55)',
              fontWeight: 600,
              textTransform: 'uppercase',
            }}
          >
            Metabolic Intelligence System
          </span>
        </div>

        {/* Headline */}
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            marginTop: 96,
            fontSize: 76,
            fontWeight: 700,
            lineHeight: 1.05,
            maxWidth: 920,
            letterSpacing: -1,
          }}
        >
          <div style={{ display: 'flex' }}>See what your cholesterol</div>
          <div style={{ display: 'flex' }}>
            is&nbsp;<span style={{ color: '#a4d65e' }}>actually</span>&nbsp;telling you.
          </div>
        </div>

        {/* Subhead */}
        <div
          style={{
            display: 'flex',
            marginTop: 32,
            fontSize: 26,
            color: 'rgba(255,255,255,0.62)',
            maxWidth: 880,
            lineHeight: 1.4,
          }}
        >
          A 3-minute finger-prick + Meo AI interpretation. Your metabolic picture, read aloud daily.
        </div>

        {/* Footer */}
        <div
          style={{
            display: 'flex',
            marginTop: 'auto',
            justifyContent: 'space-between',
            alignItems: 'center',
            fontSize: 20,
            color: 'rgba(255,255,255,0.62)',
          }}
        >
          <div style={{ display: 'flex', gap: 24 }}>
            <div style={{ display: 'flex' }}>30-day money-back</div>
            <div style={{ display: 'flex' }}>·</div>
            <div style={{ display: 'flex' }}>Ships in 48h</div>
            <div style={{ display: 'flex' }}>·</div>
            <div style={{ display: 'flex' }}>Used in 14 countries</div>
          </div>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              padding: '14px 28px',
              borderRadius: 14,
              background: '#a4d65e',
              color: '#1a3a2a',
              fontWeight: 700,
              fontSize: 22,
            }}
          >
            Get Meo · £197
          </div>
        </div>
      </div>
    ),
    { ...size },
  );
}
